# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0005_auto_20160928_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('god_mode', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_number', models.IntegerField(null=True)),
                ('cached_beta', models.FloatField(null=True)),
                ('weight', models.IntegerField()),
                ('allow_partial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemScribble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of test', max_length=50)),
                ('color', models.CharField(default='000000', help_text='Hex code for color test printed on', max_length=50)),
                ('is_indiv', models.BooleanField()),
                ('algorithm_scoring', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TestScribble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_image', models.FileField(upload_to=b'')),
                ('mathlete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.AbstractMathlete')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.AbstractTeam')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helium.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached_score', models.IntegerField(null=True)),
                ('cached_valid', models.NullBooleanField(default=None)),
                ('mathlete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.AbstractMathlete')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helium.Problem')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.AbstractTeam')),
            ],
        ),
        migrations.AddField(
            model_name='problemscribble',
            name='testscan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helium.TestScribble'),
        ),
        migrations.AddField(
            model_name='problemscribble',
            name='verdict',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='helium.Verdict'),
        ),
        migrations.AddField(
            model_name='problem',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helium.Test'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='verdict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helium.Verdict'),
        ),
    ]
