# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='verdict',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='helium.Verdict'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='cached_beta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testscribble',
            name='mathlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.AbstractMathlete'),
        ),
        migrations.AlterField(
            model_name='testscribble',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.AbstractTeam'),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='cached_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='mathlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.AbstractMathlete'),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='problem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='helium.Problem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verdict',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.AbstractTeam'),
        ),
    ]
