# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-16 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0001_squashed_0068_threadtaskrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entirepdfscribble',
            name='exam',
            field=models.ForeignKey(help_text='The exam associated to this PDF.', on_delete=django.db.models.deletion.CASCADE, to='helium.Exam'),
        ),
        migrations.AlterField(
            model_name='scorerow',
            name='category',
            field=models.CharField(help_text='Category for this score list (for example, name of exam).', max_length=80),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helium.Problem'),
        ),
    ]
