# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0002_auto_20161004_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testscribble',
            name='scan_image',
            field=models.FileField(upload_to='scans/'),
        ),
    ]
