# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-18 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0002_auto_20170116_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examscribble',
            name='needs_attention',
            field=models.CharField(blank=True, default='', help_text='Text description of an issue with this scan (no name, no such student, et cetera).', max_length=200),
        ),
    ]
