# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-01 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0003_auto_20170218_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='min_override',
            field=models.IntegerField(default=5, help_text='Number of graders required to override a grading conflict. For example, the default setting is that a 5:1 majority is sufficient to override a conflicting grade.'),
        ),
    ]
