# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0003_auto_20161004_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemscribble',
            old_name='testscan',
            new_name='testscribble',
        ),
        migrations.RemoveField(
            model_name='testscribble',
            name='scan_image',
        ),
        migrations.AddField(
            model_name='problemscribble',
            name='scan_image',
            field=models.ImageField(default=None, upload_to='scans/problems/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testscribble',
            name='name_field',
            field=models.ImageField(default=None, upload_to='scans/names'),
            preserve_default=False,
        ),
    ]
