# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-11 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0004_auto_20171201_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='verdict',
            name='scanned_at',
            field=models.DateTimeField(blank=True, help_text="When the verdict was created based on scans. None if the Verdict isn't associated to a scan. Should not be edited manually. This is actually a hack to deal with bulk_update issues", null=True),
        ),
    ]
