# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0005_auto_20161004_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verdict',
            old_name='cached_score',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='verdict',
            name='cached_valid',
        ),
        migrations.AddField(
            model_name='verdict',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verdict',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='testscribble',
            name='scan_image',
            field=models.ImageField(upload_to='scans/names/'),
        ),
    ]
