# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0006_auto_20161005_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.CharField(default='', max_length=70),
        ),
    ]
