# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-11-05 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0006_auto_20181023_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='uses_qr',
            field=models.BooleanField(default=False, help_text='Whether to enable QR codes for name matching for this test. '),
        ),
    ]
