# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0012_auto_20161006_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemscribble',
            name='problem',
        ),
        migrations.AlterUniqueTogether(
            name='evidence',
            unique_together=set([('verdict', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='examscribble',
            unique_together=set([('exam', 'mathlete', 'team')]),
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together=set([('exam', 'problem_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='verdict',
            unique_together=set([('problem', 'mathlete', 'team')]),
        ),
    ]
