# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0013_auto_20161006_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='ready',
            field=models.BooleanField(default=True, help_text='Mark true if ready to grade this exam'),
        ),
    ]
