# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0014_exam_ready'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='ready',
            new_name='is_ready',
        ),
    ]
