# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0015_auto_20161006_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='alg_scoring',
            new_name='is_alg_scoring',
        ),
    ]
