# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0016_auto_20161006_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verdict',
            name='is_done',
            field=models.BooleanField(default=False, help_text='Whether this verdict should be read by more normal users'),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='is_valid',
            field=models.BooleanField(default=True, help_text='Whether there is an answer consensus'),
        ),
        migrations.AlterUniqueTogether(
            name='examscribble',
            unique_together=set([('exam', 'team'), ('exam', 'mathlete')]),
        ),
        migrations.AlterUniqueTogether(
            name='verdict',
            unique_together=set([('problem', 'team'), ('problem', 'mathlete')]),
        ),
    ]
