# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0017_auto_20161006_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='verdict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='helium.Verdict'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='color',
            field=models.CharField(default='#FFFFFF', help_text='Color which exam is printed on (shows up when grading)', max_length=50),
        ),
    ]
