# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0018_auto_20161008_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='verdict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helium.Verdict'),
        ),
    ]
