# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20160928_0008'),
        ('helium', '0019_auto_20161008_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathleteAlpha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached_alpha', models.FloatField(blank=True, null=True)),
                ('mathlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.AbstractMathlete')),
            ],
        ),
    ]
