# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0020_mathletealpha'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='min_grades',
            field=models.IntegerField(default=3, help_text='Minimum number of graders per problem'),
        ),
        migrations.AddField(
            model_name='exam',
            name='min_override',
            field=models.IntegerField(default=3, help_text='Number of graders required to override a grading conflict.'),
        ),
    ]
