# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0021_auto_20161008_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='cached_beta',
            field=models.FloatField(blank=True, default=3),
        ),
    ]
