# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0022_auto_20161011_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='cached_beta',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
