# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0023_auto_20161011_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_team', models.BooleanField(default=False)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helium.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='EntityAlpha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached_alpha', models.FloatField(blank=True, null=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='helium.Entity')),
            ],
        ),
        migrations.AddField(
            model_name='examscribble',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helium.Entity'),
        ),
        migrations.AddField(
            model_name='verdict',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helium.Entity'),
        ),
        migrations.AlterUniqueTogether(
            name='verdict',
            unique_together=set([('problem', 'entity')]),
        ),
        migrations.AlterUniqueTogether(
            name='examscribble',
            unique_together=set([('exam', 'entity')]),
        ),
        migrations.RemoveField(
            model_name='mathletealpha',
            name='mathlete',
        ),
        migrations.RemoveField(
            model_name='examscribble',
            name='mathlete',
        ),
        migrations.RemoveField(
            model_name='examscribble',
            name='team',
        ),
        migrations.RemoveField(
            model_name='verdict',
            name='mathlete',
        ),
        migrations.RemoveField(
            model_name='verdict',
            name='team',
        ),
        migrations.DeleteModel(
            name='MathleteAlpha',
        ),
    ]
