# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0025_auto_20161012_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='number',
            field=models.IntegerField(blank=True, help_text="You can assign (unique) numbers here if you can't assume names are pairwise distinct.This isn't used internally by Helium itself.", null=True),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together=set([('is_team', 'number')]),
        ),
    ]
