# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0030_gutsfunc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GutsFunc',
            new_name='GutsScoreFunc',
        ),
    ]
