# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0031_auto_20161021_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='gutsscorefunc',
            name='description',
            field=models.CharField(default='', help_text='A brief description of the problem, for admin interface use', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gutsscorefunc',
            name='scoring_function',
            field=models.TextField(default='function (x) {\n\treturn Math.min(0, 20-Math.abs(49-x));\n}', help_text='Javascript syntax for a one-variable function. This is the score reported if a staff member enters input x.\nCan span multiple lines.'),
        ),
    ]
