# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0033_auto_20161021_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gutsscorefunc',
            name='answer',
            field=models.CharField(help_text='True answer for problem, not actually used by model, shown in grader.', max_length=80),
        ),
        migrations.AlterField(
            model_name='gutsscorefunc',
            name='description',
            field=models.CharField(blank=True, help_text='A brief description of the problem, shown only in admin interface.', max_length=80),
        ),
        migrations.AlterField(
            model_name='gutsscorefunc',
            name='problem_help_text',
            field=models.CharField(blank=True, default='Input an integer.', help_text='An optional text that will display to help the staff member. For example, `input a string of seven letters`.', max_length=120),
        ),
        migrations.AlterField(
            model_name='gutsscorefunc',
            name='scoring_function',
            field=models.TextField(default='function (x) {\n\treturn Math.max(0, 20-Math.abs(49-x));\n}', help_text='Javascript syntax for a one-variable function. This is the score reported if a staff member enters input x.\nCan span multiple lines.'),
        ),
    ]
