# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-23 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0034_auto_20161021_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='score',
            field=models.IntegerField(help_text='The score assigned by the user'),
        ),
    ]
