# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-23 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0035_auto_20161023_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='god_mode',
            field=models.BooleanField(default=False, help_text='If enabled, this piece of evidence is in GOD MODE. That means that all other evidences are ignored for that verdict.If more than one evidence is in God mode, the verdict will be marked invalid. '),
        ),
    ]
