# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-29 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0037_auto_20161029_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examscribble',
            old_name='scan_image',
            new_name='name_image',
        ),
        migrations.RenameField(
            model_name='problemscribble',
            old_name='scan_image',
            new_name='prob_image',
        ),
    ]
