# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-29 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0038_auto_20161029_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_alg_scoring',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_indiv',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.CharField(blank=True, default='', help_text='The answer for a problem, which is shown in help texts.', max_length=70),
        ),
    ]
