# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-29 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0039_auto_20161029_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='color',
            field=models.CharField(default='#FFFFFF', help_text="Color which exam is printed on. Grading pages will be tinted with this color so that e.g. we don't accidentally have someone enter Algebra scores into Geometry. (This was a very common mistake in old Babbage.) This color is page background so it should be VERY light (like #EEFFEE light).", max_length=50),
        ),
    ]
