# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-29 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0041_auto_20161029_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntireScanPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('scan_pdf', models.FileField(null=True, upload_to='scans/pdfs/')),
            ],
        ),
        migrations.AddField(
            model_name='examscribble',
            name='pdf',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='helium.EntireScanPDF'),
            preserve_default=False,
        ),
    ]
