# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-29 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0042_auto_20161029_2229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntireScanPDF',
            new_name='EntirePDFScribble',
        ),
        migrations.RenameField(
            model_name='examscribble',
            old_name='pdf',
            new_name='pdf_scribble',
        ),
    ]
