# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-29 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0043_auto_20161029_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entirepdfscribble',
            name='name',
            field=models.CharField(help_text='The name of the PDF file, which must be unique (this is a safety feature to prevent accidental double uploads). ', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='entirepdfscribble',
            name='scan_pdf',
            field=models.FileField(help_text='The scanned PDF file itself.', null=True, upload_to='scans/pdfs/'),
        ),
        migrations.AlterField(
            model_name='examscribble',
            name='exam',
            field=models.ForeignKey(help_text='The exam associated to an exam scribble file.', on_delete=django.db.models.deletion.CASCADE, to='helium.Exam'),
        ),
        migrations.AlterField(
            model_name='examscribble',
            name='pdf_scribble',
            field=models.ForeignKey(help_text='The PDF from which the exam scribble comes from.', on_delete=django.db.models.deletion.CASCADE, to='helium.EntirePDFScribble'),
        ),
    ]
