# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-29 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0044_auto_20161029_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entirepdfscribble',
            old_name='scan_pdf',
            new_name='scan_file',
        ),
    ]
