# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-29 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0045_auto_20161029_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='entirepdfscribble',
            name='is_done',
            field=models.BooleanField(default=False, help_text='Whether the PDF is done scanning.'),
        ),
    ]
