# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-30 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0047_problemscribble_last_sent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemscribble',
            name='last_sent_time',
            field=models.IntegerField(blank=True, help_text='Most recent time the scan was sent out (in seconds since Epoch);reset to None when the problem is graded. This prevents the scan grader from accidentally giving duplicates.', null=True),
        ),
    ]
