# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0050_entirepdfscribble_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='examscribble',
            name='needs_attention',
            field=models.BooleanField(default=False, help_text='If the exam scribble needs special attention in some way (scanned upside-down, illegible, etc.)'),
        ),
    ]
