# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0051_examscribble_needs_attention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examscribble',
            name='needs_attention',
            field=models.BooleanField(default=False, help_text='If this scan needs special attention in some way (upside-down, illegible, etc.)'),
        ),
    ]
