# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-05 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0052_auto_20161103_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(help_text='Name of exam', max_length=50, unique=True),
        ),
    ]
