# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-14 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0053_auto_20161105_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examscribble',
            name='needs_attention',
            field=models.CharField(blank=True, default='', help_text='Text description of an issue with this scan (no name, no such student, et cetera).', max_length=80),
        ),
        migrations.AlterField(
            model_name='gutsscorefunc',
            name='scoring_function',
            field=models.TextField(default='function (x) {\n\treturn Math.round(Math.max(0, WEIGHT-Math.abs(ANS-x)));\n}', help_text='Javascript syntax for a one-variable function. This is the score reported if a staff member enters input x.\nCan span multiple lines.'),
        ),
    ]
