# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-14 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0054_auto_20161114_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='examscribble',
            name='last_sent_time',
            field=models.IntegerField(blank=True, help_text='Most recent time the scan was sent out (in seconds since Epoch);this prevents the name-match from giving duplicates.', null=True),
        ),
    ]
