# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0055_auto_20161115_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityexamscores',
            name='category',
            field=models.CharField(default='', help_text='Category for this score list (for example, name of exam).', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entityexamscores',
            name='total_score',
            field=models.FloatField(default=0, help_text='Total score'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='entityexamscores',
            unique_together=set([('category', 'entity')]),
        ),
    ]
