# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0056_auto_20161115_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityexamscores',
            name='rank',
            field=models.IntegerField(default=0, help_text='Relative rank of this result row'),
            preserve_default=False,
        ),
    ]
