# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0057_entityexamscores_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityexamscores',
            name='total_score',
        ),
        migrations.AddField(
            model_name='entityexamscores',
            name='total',
            field=models.FloatField(default=0, help_text='Total score'),
        ),
    ]
