# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0058_auto_20161115_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntityExamScores',
            new_name='ScoreRow',
        ),
    ]
