# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0059_auto_20161115_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerow',
            name='rank',
            field=models.IntegerField(help_text='Relative rank of this result row', null=True),
        ),
    ]
