# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0060_auto_20161115_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerow',
            name='cached_score_string',
            field=models.CharField(blank=True, default='', help_text='A comma-separated list of float values which are scores for that exam.', max_length=400),
        ),
    ]
