# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0061_auto_20161115_1403'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scorerow',
            unique_together=set([]),
        ),
    ]
