# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0064_auto_20161115_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerow',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helium.Entity'),
        ),
        migrations.AlterUniqueTogether(
            name='scorerow',
            unique_together=set([('category', 'entity')]),
        ),
    ]
