# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-16 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0065_auto_20161115_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='can_upload_scan',
            field=models.BooleanField(default=False, help_text='Mark true if you want users to be able to upload scans this exam. You should set it to False after all exams are scanned, to decrease the chance that someone uploads a scan to the wrong place.'),
        ),
    ]
