# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-23 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helium', '0055_examscribble_last_sent_time'),
        ('helium', '0066_exam_can_upload_scan'),
    ]

    operations = [
    ]
