# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-23 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helium', '0067_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadTaskRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the task being fired', max_length=80)),
                ('status', models.NullBooleanField(help_text='True for success and False for failed task')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('output', models.TextField(help_text='Output from the task')),
                ('user', models.ForeignKey(help_text='This is the user requesting the task', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
